# Site settings
title: Amanda's blog
email: ajzapata4@gmail.com
description: > # This means to ignore newlines until "baseurl:"
  I am cool and stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://azap4.github.io" # the base hostname & protocol for your site
twitter_username: ajzapata
github_username:  azap4
permalink: /:title/

# Build settings
markdown: kramdown
